name: Ubuntu Build

on:
  workflow_call:

jobs:
  build:
    runs-on: ${{ matrix.arch == 'amd64' && 'ubuntu-latest' || 'ubuntu-24.04-arm' }}
    strategy:
      matrix:
        include:
        - arch: amd64
          name: ubuntu-24.04-amd64
        - arch: arm64
          name: ubuntu-24.04-arm64

    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential libwebkitgtk-6.0-dev

    - name: Checkout ring-simplejson
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Clone Ring Language
      uses: actions/checkout@v4
      with:
        repository: ringpackages/ringsrc
        path: ring

    - name: Build and Install Ring Language
      run: |
        cd ring/language
        cmake . -DCMAKE_BUILD_TYPE=Release
        make install

    - name: Set RING environment variable
      run: echo "RING=$(pwd)/ring" >> $GITHUB_ENV

    - name: Build ring-simplejson lib
      run: |
        rm -rf lib
        cmake . -DCMAKE_BUILD_TYPE=Release
        make

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ring-simplejson-${{ matrix.name }}
        path: lib
